### ISSUE TITLE
multi node instance use broadcastStateless crashed

### ISSUE THREAD

**Issue by groot9325** [ueberdosis/hocuspocus#558]
**Description**
multi node instance use broadcastStateless crashed, and I submitted a pr #556 

**Steps to reproduce the bug**
1. There are 2 hocuspocus instance managed by pm2, which connect to the same redis with extension-redis, and the 2 hocuspocus instance  listen port 3001 and 3002. 
2. Client1 connect 3001  and Client2 connect 3002, 
3. If client1 call `provider.sendStateless('hello')` and hocuspocus-instance1 will broadcast msg to all connctions which will  publish message to Redis channel through  beforeBroadcastStateless
```async beforeBroadcastStateless(data: beforeBroadcastStatelessPayload) {
    const message = new OutgoingMessage()
      .writeBroadcastStateless(data.payload)

    return this.pub.publishBuffer(
      this.pubKey(data.documentName),
      Buffer.from(message.toUint8Array()),
    )
  }
  ```
 
4. Client2 recevied message through 
```typescript
   this.sub.on('pmessageBuffer', this.handleIncomingMessage) 
```
  and handle it in 
  ```typescript
    private handleIncomingMessage = async (channel: Buffer, pattern: Buffer, data: Buffer) => {
    const channelName = pattern.toString()
    const [_, documentName, identifier] = channelName.split(':')
    const document = this.documents.get(documentName)

    if (identifier === this.configuration.identifier) {
      return
    }

    if (!document) {
      return
    }

    new MessageReceiver(
      new IncomingMessage(data),
      this.logger,
    ).apply(document, undefined, reply => {
      return this.pub.publishBuffer(
        this.pubKey(document.name),
        Buffer.from(reply),
      )
    })
  }

   //and in apply function will call 
    ...
    case MessageType.BroadcastStateless:
        document.getConnections().forEach(connection => {
          connection.sendStateless(message.readVarString()) 
        })
    
  ```
the `message.readVarString()` will cause crash because message can only read once, when read Again it will throw Integer out of range if we try and catch apply function.

and the the readVarString in lib0/decoding.js as follow, message is like an stream, offset pos will change after readVarString or readVarUint
```
export const readVarString = decoder => {
  let remainingLen = readVarUint(decoder)
  if (remainingLen === 0) {
    return ''
  } else {
    let encodedString = String.fromCodePoint(readUint8(decoder)) // remember to decrease remainingLen
    if (--remainingLen < 100) { // do not create a Uint8Array for small strings
      while (remainingLen--) {
        encodedString += String.fromCodePoint(readUint8(decoder))
      }
    } else {
      while (remainingLen > 0) {
        const nextLen = remainingLen < 10000 ? remainingLen : 10000
        // this is dangerous, we create a fresh array view from the existing buffer
        const bytes = decoder.arr.subarray(decoder.pos, decoder.pos + nextLen)
        decoder.pos += nextLen
        // Starting with ES5.1 we can supply a generic array-like object as arguments
        encodedString += String.fromCodePoint.apply(null, /** @type {any} */ (bytes))
        remainingLen -= nextLen
      }
    }
    return decodeURIComponent(escape(encodedString))
  }
}
```

and now the error happen:
```
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
Error: Integer out of range!
    at readVarUint (file:///export/backend/node_modules/node_modules/lib0/decoding.js:247:13)
    at readVarString (file:///export/backend/node_modules/node_modules/lib0/decoding.js:328:22)
    at IncomingMessage.readVarString (file:///export/backend/node_modules/@hocuspocus/server/src/IncomingMessage.ts:46:12)
    at file:///export/backend/node_modules/@hocuspocus/server/src/MessageReceiver.ts:82:44
    at Array.forEach (<anonymous>)
    at MessageReceiver.apply (file:///export/backend/node_modules/@hocuspocus/server/src/MessageReceiver.ts:81:35)
    at Redis.handleIncomingMessage (file:///export/backend/node_modules/@hocuspocus/extension-redis/src/Redis.ts:282:7)
    at Redis.emit (events.js:400:28)
    at DataHandler.handleSubscriberReply (/export/backend/node_modules/ioredis/built/DataHandler.js:89:28)
    at DataHandler.returnReply (/export/backend/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/export/backend/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/export/backend/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/export/backend/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:293:12)
    at readableAddChunk (internal/streams/readable.js:267:9)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```

hocuspocus configure like this.
```typescript
  const server = Server.configure({
  name: 'hocuspocus-instance',
  port: config.server.port, // managed by pm2 range[3001, 3002]
  address: config.server.host,
  extensions: [
    new Redis({
      host: config.redis.host,
      port: config.redis.port,
      options:{
        password: config.redis.password,
      },
      prefix:config.redis.keyPrefix,
    }),
  ],
  async connected() {
    console.log('connections:', server.getConnectionsCount())
  },
  async onStateless(data:onStatelessPayload) {
    const { connection, documentName, document, payload} = data
    const info = JSON.stringify({"event":"this is a broadcast msg"})
    document.broadcastStateless(info)
  },
})

server.listen()
```

**Expected behavior**
Client A and Client B can receive broadcast messages through the redis channel

**Screenshot, video, or GIF**

**Environment?**
 - operating system: CentOS Linux release 7.9.2009 (Core)
 - browser:  chrome 111.0.5563.111 
 - mobile/desktop:
 - Hocuspocus version: 1.1.1

**Additional context**

**Comment by janthurau** [comment]
Thanks! I've just released v2.0.1 including your fix :)
