### ISSUE TITLE
y-websocket provider throws unknown type error and RangeError with Hocuspocus server

### ISSUE THREAD

**Issue by alexazarh** [ueberdosis/hocuspocus#591]
**Description**
y-websocket provider doesn't work with Hocuspocus server. However when the y-websocket is switched with the HocuspocusProvider it works.

**Steps to reproduce the bug**
My server setup is very simple:
`const server = new Hocuspocus({
  port: 8000
});
server.listen();
`
In the client I have a yjs doc with 2 maps.
The HocuspocusProvider client works as expected but when I try to use the yjs WebsocketProvider the server shows the following errors:

_[1] closing connection because of exception Error: Received a message with an unknown type: 222
[1]     at MessageReceiver.readSyncMessage (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:1639:23)
[1]     at MessageReceiver.apply (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:1518:22)
[1]     at C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:1811:55
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[1] closing connection because of exception RangeError: Invalid typed array length: 1239384915
[1]     at new Uint8Array (<anonymous>)
[1]     at createUint8ArrayViewFromArrayBuffer (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:734:77)
[1]     at readUint8Array (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:822:16)
[1]     at readVarUint8Array (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:837:38)
[1]     at IncomingMessage.readVarUint8Array (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:947:16)
[1]     at MessageReceiver.apply (C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:1541:66)
[1]     at C:\work\git\ca-backend\services\nodes-ms\node_modules\@hocuspocus\server\dist\hocuspocus-server.cjs:1811:55
[1]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)_

**Expected behavior**
The expected behavior for the yjs WebsocketProvider is to work with the Hocuspocus server and be interchangeable with the HocuspocusProvider client provider

**Screenshot, video, or GIF**
![image](https://user-images.githubusercontent.com/6730546/234687125-a37a2a01-2c1c-425c-92e0-695f389e8834.png)

**Environment?**
 - operating system: Windows 11
 - browser: Chrome
 - Hocuspocus version: 2.0.6
 - Node version: 18.15.0

**Additional context**
The yjs document contains information for nodes and edges from reactflow

**Comment by janthurau** [comment]
@alexazarh We are not compatible with y-websocket provider.

**Comment by alexazarh** [comment]
@janthurau In this case it's worth updating the docs. According to this page you are compatible:

> You can use the Hocuspocus server with y-websocket, the Hocuspocus provider with the y-websocket server, the Hocuspocus provider with y-webrtc … whatever you like.
https://tiptap.dev/hocuspocus/provider/introduction

**Comment by janthurau** [comment]
ohhh shit! Thanks for the hint. Updating right away.
