### ISSUE TITLE
CLI fails to run server, error: The option `alias` has been renamed to `shortFlag`. The following flags need to be updated: `--port`, `--webhook`, `--sqlite`

### ISSUE THREAD

**Issue by alexkreidler** [ueberdosis/hocuspocus#623]
**Description**
CLI fails to run server

**Steps to reproduce the bug**
1. Run `pnpx @hocuspocus/cli` or `pnpm install @hocuspocus/cli` and `pnpm exec hocuspocus`
2. See this output:
```
flow/node_modules/.pnpm/meow@12.0.1/node_modules/meow/source/options.js:52
                throw new Error(errorMessages.join('\n'));
                      ^

Error: The option `alias` has been renamed to `shortFlag`. The following flags need to be updated: `--port`, `--webhook`, `--sqlite`
    at validateOptions (file:///flow/node_modules/.pnpm/meow@12.0.1/node_modules/meow/source/options.js:52:9)
    at buildOptions (file:///flow/node_modules/.pnpm/meow@12.0.1/node_modules/meow/source/options.js:87:2)
    at meow (file:///flow/node_modules/.pnpm/meow@12.0.1/node_modules/meow/source/index.js:91:24)
    at file:///flow/node_modules/.pnpm/@hocuspocus+cli@2.1.0_@tiptap+pm@2.0.3_y-prosemirror@1.2.1_y-protocols@1.0.5_yjs@13.6.2/node_modules/@hocuspocus/cli/src/index.js:9:20
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Node.js v18.14.0
```

**Expected behavior**
The server should start successfully

**Environment?**
 - operating system: Ubuntu 20.04
 - Hocuspocus version:
 ```
    "@hocuspocus/cli": "^2.1.0",
    "@hocuspocus/provider": "^2.1.0",
    "@hocuspocus/server": "^2.1.0",
```

**Comment by StanislavLakhtin** [comment]
Description: can't run CLI seerver
OS: MacOS 13.3.1

### How to reproduce the bug

Install

```
Need to install the following packages:
  @hocuspocus/cli@2.1.0
Ok to proceed? (y) y
...
```

Run

```
npx @hocuspocus/cli --p 1234 --sqlite
```
output

```
npx @hocuspocus/cli --p 1234 --sqlite           1 ✘  4s
file:///Users/bb/.npm/_npx/a57a221d08bbf04d/node_modules/meow/source/options.js:52
		throw new Error(errorMessages.join('\n'));
		      ^

Error: The option `alias` has been renamed to `shortFlag`. The following flags need to be updated: `--port`, `--webhook`, `--sqlite`
    at validateOptions (file:///Users/bb/.npm/_npx/a57a221d08bbf04d/node_modules/meow/source/options.js:52:9)
    at buildOptions (file:///Users/bb/.npm/_npx/a57a221d08bbf04d/node_modules/meow/source/options.js:87:2)
    at meow (file:///Users/bb/.npm/_npx/a57a221d08bbf04d/node_modules/meow/source/index.js:91:24)
    at file:///Users/bb/.npm/_npx/a57a221d08bbf04d/node_modules/@hocuspocus/cli/src/index.js:9:20
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
```

**Comment by janthurau** [comment]
sorry, forgot to release the fix.

As soon as you use 2.2.0, it'll work 🥳 

https://github.com/ueberdosis/hocuspocus/releases/tag/v2.2.0
